Logger
mini-services/miniurl pull request #112
Opened 2021-02-28 12:44 UTC by AviadSofer

Hi
add kind of Logger to the Repo.
not finel yet:)

2021-02-28 19:01 UTC, SnirShechter requested changes

2021-02-28 19:01 UTC, SnirShechter commented on src/services/storage/index.ts
> +			// סליחה על העברית, התוצאה שמוחזרת היא לכאורה רגישה, אז כרגע זה בקומיט
This is actually not sensitive. You can remove the Hebrew and add the logger.

**What's sensitive?**
Database credentials, admin token, personal information (which we currently don't have).

**What's _not_ sensitive?**
ids, URLs (without tokens in the query etc.), IPs and anything else.

2021-03-01 12:37 UTC, AviadSofer commented on src/config/validate.ts
> +	logger.debug(`Start validateStorageDriver with ${storageValues}`)
ok:)
actually, I tried. if you print just `storage ` itself, it's will print just "Obj"

2021-03-01 12:54 UTC, AviadSofer commented on src/services/logger/logger.ts
> +	console.log(`Logger: Level changed to ${logger.level}`)
Hi.
If we will change this to debug, while the level define as a "warn" for exemple, it's will not print anything.
You can see this [here](https://github.com/pinojs/pino/blob/master/docs/api.md#event-level-change).

2021-03-03 08:31 UTC, SnirShechter requested changes

2021-03-03 08:31 UTC, SnirShechter commented on src/config/index.ts
> +import { logger } from '../services/logger/logger.js'
Remove this (unused import)

2021-03-03 08:31 UTC, SnirShechter commented on src/config/index.ts
> +	logger.error('rawConfig is not validated')
```suggestion
	logger.error('Recieved config is invalid')
```

These logs will be seen by users. They don't know what RawConfig means.

2021-03-03 08:31 UTC, SnirShechter commented on src/index.ts
> +logger.info(`Logger level define as ${config.logLevel}`)
```suggestion
logger.info(`Logger level defined as ${config.logLevel}`)
```

2021-03-04 08:05 UTC, SnirShechter commented on src/config/validate.ts
> +	logger.debug(`Start validateStorageDriver with ${storageValues}`)
You can print it as `logger.debug(`...`, storage)

2021-03-04 08:41 UTC, SnirShechter requested changes

2021-03-04 08:41 UTC, SnirShechter commented on src/services/storage/index.ts
> +				throw new GeneralError('Could not save (Storage.url.save)')
Remember that these errors are returned to the client, so don't add the function name here.
```suggestion
				throw new GeneralError('Could not save url')
```

2021-03-04 08:41 UTC, SnirShechter commented on src/services/storage/index.ts
> +			throw new GeneralError('Could not initialize (Storage.initialize)')
Can you throw the actual error here? This function is not propagated back to the client, so it's safe to throw it
```suggestion
			throw err
```

2021-03-04 08:41 UTC, SnirShechter commented on src/services/storage/index.ts
> +				logger.error(`Storage.url.get failed: ${err}`)
Did you check that these logs actually show the error well? If they do, just ignore this comment.

2021-03-04 08:41 UTC, SnirShechter commented on src/services/auth/index.ts
> +		logger.debug(`Running isAuthorized`)
```suggestion
		logger.debug(`Running Auth.isAuthorized`)
```

2021-03-04 08:41 UTC, SnirShechter commented on src/services/auth/index.ts
> +		logger.debug(`Running authorize`)
```suggestion
		logger.debug(`Running Auth.authorize`)
```

2021-03-04 08:41 UTC, SnirShechter commented on src/services/auth/drivers/bearerToken/index.ts
> +		logger.debug(`Running authorize`)
```suggestion
		logger.debug(`Running BearerTokenAuth.authorize`)
```

2021-03-04 08:41 UTC, SnirShechter commented on src/services/auth/drivers/bearerToken/index.ts
> +		logger.debug(`Running isAuthorized`)
```suggestion
		logger.debug(`Running BearerTokenAuth.isAuthorized`)
```

2021-03-04 08:41 UTC, SnirShechter commented on src/index.ts
> +logger.info(`Logger level define as ${config.logLevel}`)
```suggestion
logger.info(`Logger level defined as ${config.logLevel}`)
```

2021-03-04 08:41 UTC, SnirShechter commented on src/config/index.ts
>  	console.info(`Generated bearer token is '${rawConfig.auth.bearerTokenDriverConfig.token}'`)
```suggestion
	logger.info(`Generated bearer token is '${rawConfig.auth.bearerTokenDriverConfig.token}'`)
```

2021-03-06 20:28 UTC, SnirShechter commented
Closes #21
Closes #80

2021-03-06 20:29 UTC, SnirShechter approved these changes

2021-03-06 20:29 UTC, merged