redisDB
mini-services/miniurl pull request #125
Opened 2021-03-07 10:51 UTC by shay123g

2021-03-07 10:55 UTC, shay123g commented
close #29

2021-03-08 07:56 UTC, Danielg212 reviewed
try to reduce the switch case to more abstract method

2021-03-08 07:56 UTC, Danielg212 commented on src/errors/invalidUrl.ts
> +	undefined,
I think this should be 400 code

2021-03-08 07:56 UTC, Danielg212 commented on src/helpers/redisHelper.ts
> +	generateUrl(key: string, value: string): void{
can you abstract this method? - remove the switch case and use more abstract method

2021-03-08 07:56 UTC, Danielg212 commented on src/services/storage/drivers/redis/index.ts
> +				ip: url.ip != '' ? url.ip : 'undefined',
you can write this as `url.ip?url.ip: undefined `

2021-03-08 09:07 UTC, SnirShechter requested changes

2021-03-08 09:07 UTC, SnirShechter commented on src/services/storage/drivers/redis/types.ts
> +export interface RedisStorageDriverConfig {}
The Redis driver doesn't need any configuration? what about the URL? possible credentials?

2021-03-13 15:37 UTC, closed without merging