Documentation fixes
mini-services/miniurl pull request #88
Opened 2021-02-11 15:45 UTC by shay123g

need add new line after "depends on OS Linux"

so it will be
depends on OS
Linux

Hope I am right in the instructions

2021-02-11 20:00 UTC, SnirShechter commented
I'm not sure this is the correct spot to place it.

I think we should just write:
```
Requirements:
* Node.js 14.8+
* NPM 6+ or Yarn X+
```

The nvm usage should be a separate troubleshooting Q&A. Possibly link to the nvm docs instead of writing your own (if it's good enough for us).

2021-02-11 20:00 UTC, SnirShechter requested changes

2021-02-12 10:09 UTC, shay123g commented
> I'm not sure this is the correct spot to place it.
> 
> I think we should just write:
> 
> ```
> Requirements:
> * Node.js 14.8+
> * NPM 6+ or Yarn X+
> ```
> 
> The nvm usage should be a separate troubleshooting Q&A. Possibly link to the nvm docs instead of writing your own (if it's good enough for us).

agreed

2021-02-15 08:20 UTC, SnirShechter approved these changes

2021-02-15 08:20 UTC, merged